language: php
php:
 - 5.2
 - 5.3
 - 5.4
 - 5.5

branches:
  except:
    - 1.0
    - 1.5
    - 1.6
    - 1.7
    - 1.8

matrix:
  include:
    - php: 5.3
      env: VARIA=true
      install:
       - phpenv rehash
       - composer update squizlabs/php_codesniffer elgg/sniffs --prefer-source
       - npm install
       - sudo easy_install "Sphinx==1.1.3"
       - sudo easy_install "sphinx-intl"
       - wget https://scrutinizer-ci.com/ocular.phar
      script:
       - bash .scripts/travis/check_commit_msgs.sh
       - vendor/bin/phpcs --standard=vendor/elgg/sniffs/elgg.xml --warning-severity=0 --ignore=*/tests/*,*/upgrades/*,*/deprecated* engine/classes engine/lib
       - npm test
         # Flags used here, not in `make html`:
         #  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
         #  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
       - sphinx-build -b html -nW docs docs/_build/html
       - sphinx-build -b latex -nW docs docs/_build/latex
       - sphinx-intl --locale-dir=docs/locale/ build
       - sphinx-build -b html -D language=es -n docs docs/_build/html
       - phpunit --coverage-clover=coverage.clover
       - composer validate
      after_script:
       - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

services:
 - mysql

before_script:
 - mysql -e 'create database elgg;'
 - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root
 - mkdir "${HOME}/elgg_data/"
 - php -f ./install/cli/travis_installer.php

script:
 - phpunit
 - php -f ./engine/tests/suite.php

notifications:
  email:
    secure: exC/ws07lLOj3Y43C89jiaKpyB8Yt7DPGSCShV4R3Wkw/hVVzjxt1BinPxzsyL5DC7APUMcTHGOhDB2oCE4ynDE6o6L9bH79fc+V8IYAiNaEIGL0AOuHdnRdGN9GMrr2jv78cZ5MctuUTkeYLaoOEyDGHmkMhqa6SufIDAY8b58=
